### ISSUE TITLE
Use the Windows Packaging Project in VS to produce the APPX/MSIX

### ISSUE THREAD

**Issue by rido-min** [bsonnino/FinCalcAddIn#1]
Hi,

The Visual Studio [Windows Packaging Project](https://aka.ms/wapproj) allows to package binaries produced with other IDEs by following the next instructions:

- Add the binaries (.EXE, .DLL) to the wapproj, and mark those as Content/CopyToOutput
- Edit the `.wapproj` to specify the entry point by adding the property:
```xml
<EntryPointExe Include="Relative\PathTo.EXE" />
```
- Create Packages using the Store Wizard, or CLI builds

**Comment by bsonnino** [comment]
Hi Rido,

Thanks for pointing it out, I am thinking to write an article about creating an MSIX project for Delphi apps. Is it ok to send you an email when I finish it, so you can take a look at it?

Bruno

**Comment by rido-min** [comment]
of course !! you can find me in rmpablos at microsoft

**Comment by bsonnino** [comment]
Thanks!
