### ISSUE TITLE
Need IAPWrapper.dll

### ISSUE THREAD

**Issue by carloBarazzetta** [bsonnino/FinCalcAddIn#2]
Hi Bruno, I need to implement purchase-inapp in my Delphi win32 app.
I need IAPWrapper.dll but is not present in your project.
Can you commit the IAPWrapper.dll or I need to build a specific .dll for my app in the store?

**Comment by bsonnino** [comment]
Please, check this article for creating the DLL: https://docs.microsoft.com/en-us/archive/blogs/appconsult/enable-in-app-product-purchases-for-desktop-bridge-converted-desktop-applications

You can also check my article in my blog that explains the usage of TWindowsStore component: https://blogs.msmvps.com/bsonnino/2019/02/26/monetizing-your-delphi-app-with-twindowsstore/

**Comment by carloBarazzetta** [comment]
Thank you Bruno for your answer, but I've already read the articles and try to build the dll by myself, but when my Delphi app starts, raises an exception when trying to static link the dll... I don't know why. It's for this reason that I'm asking you the dll already compiled by you... because opening this Delphi project I see the IAPWrapper.dll inside the project tree but it was not committed...
Thank you.
Carlo

**Comment by bsonnino** [comment]
I added it now.

**Comment by carloBarazzetta** [comment]
Thank you very much!
